apiVersion : apps/v1
kind: Deployment
metadata:
  name: troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshooting
  template:
    metadata:
      labels:
        app: troubleshooting
    spec:
      containers:
        - name: troubleshooting
          image: cepgbaseacr.azurecr.io/troubleshooting:lastest
          ports:
          - containerPort: 8080
