apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: troubleshooting-ingress
spec:
  ingressClassName: ingress-internal
  rules:
  - host: ts-99999598.cepg-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: troubleshooting
            port:
              number: 8080
        pathType: Prefix